### ISSUE TITLE
rename profile .c files to match service short name

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac-stm32x0#24]
in jacdac-msr-modules, slider.c should be potentiometer.c, etc... It makes it easier to find an implemention in VS Code and in general should be a good naming convention.
- [ ] filename match short name of service
- [ ] APIs match short name of service, e.g. btn_init --> button_init, temp_init -> thermometer_init

etc...

**Comment by mmoskal** [comment]
renamed prefixes, but I left the files - the best way to look for examples is to grep for "button_init" or similar - name matching won't work in many cases, like thermometer+humidity sensor; also I find it more useful to only see the service files when I open `button` in VS Code - there's too many targets that just call the init function
