### ISSUE TITLE
implement LED service

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac-stm32x0#29]
https://microsoft.github.io/jacdac-docs/services/led/

**Comment by mmoskal** [comment]
implemented in https://github.com/microsoft/jacdac-c/commit/a182afce8641fe4babb3682c7d834eb7a6462af3

**Comment by mmoskal** [comment]
done in https://github.com/microsoft/jacdac-c/commit/c159f1b0dfe35db5063aea43063796e56ab9761d
