### ISSUE TITLE
node webusb does not read classCode/subclassCode properly

### ISSUE THREAD

**Issue by pelikhan** [microsoft/jacdac-stm32x0#6]
When trying jacdac-ts with nodewebusb, we never detect a device because it does not seem to read classCode/subclassCode properly.

![image](https://user-images.githubusercontent.com/4175913/99073181-4a67a680-256a-11eb-8d78-7ca9dd89744b.png)

**Comment by mmoskal** [comment]
Maybe we could check for bcdDevice 0x4201 ?

**Comment by pelikhan** [comment]
https://github.com/thegecko/webusb/issues/74
