### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by tballmsft** [microsoft/jacdac-stm32x0#8]
got everything installed and compiling proceeding nicely until this:

```
/home/tball/JD/jacdac-stm32x0/scripts/patch-bin.js:51
if ((w0 & 0xff00_0000) == 0x2000_0000) {
          ^^^^^^

SyntaxError: Invalid or unexpected token
```

**Comment by mmoskal** [comment]
you need to update your node.js

**Comment by mmoskal** [comment]
added workaround in https://github.com/microsoft/jacdac-stm32x0/commit/6160562f7f7f2ac889101ee9807e59caf3bdc2c7
